spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/harmonic
    username: postgres
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation=: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


server:
  port: 8083
emesbee:
  app:
    jwtSecret: ${JWT_SECRET}
