spring:
  datasource:
    url: jdbc:postgresql://${AWS_POSTGRES_DB_HOST}:${AWS_POSTGRES_DB_PORT}/${AWS_POSTGRES_DB_NAME}
    username: ${AWS_POSTGRES_DB_USERNAME}
    password: ${AWS_POSTGRES_DB_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation=: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8087
emesbee:
  app:
    jwtSecret: ${JWT_SECRET}
